### ISSUE TITLE
fire for player 2 not working

### ISSUE THREAD

**Issue by marchunter** [krystiankaluzny/Tanks#5]
Hi, the game is a lot of fun, but when playing it on linux, the left control key for player 2 is not working. Please fix the bug or would you mind pointing out where in the source do we need to change it?

**Comment by Aki78** [comment]
Hi, The bug was in src/appconfig.cpp. Change P1_FIRE_KEY SDL_SCANCODE_RCTRL to  P1_FIRE_KEY SDL_SCANCODE_LCTRL.

**Comment by marchunter** [comment]
Thanks it worked for me changing what you described, but for P2_FIRE_KEY SDL_SCANCODE_RCTRL to P2_FIRE_KEY SDL_SCANCODE_LCTRL instead

**Comment by krystiankaluzny** [comment]
@Aki78 @marchunter thank you for reporting the issue. I replaced RCTRL with LCTRL for Player 2, it should work now.
