### ISSUE TITLE
No Sound/Audio

### ISSUE THREAD

**Issue by LiangPingPiJiu** [krystiankaluzny/Tanks#7]
Hi,

thanks for the great game!
I could compile without any problems on debian stretch but I have no sound/ no audio at all. Is this correct or is there a problem with my system?

Thanks,
LiangPingPiJiu

**Comment by hybcloud** [comment]
Of course there's no support for audio.
I don't know why you think the project has audio support? You can easily find that there's no code or resource for audio in the project once you've explored it for 10 minutes.

哥们儿你稍微看看工程，光看文件名都知道没对音频做支持啊。

**Comment by LiangPingPiJiu** [comment]
Ok thank you!
I indeed looked for and didn't find, just wanted to be sure it's not hidden in this SDL stuff...

**Comment by hybcloud** [comment]
that sdl dir in resource dir should only be a precompiled sdl2 lib for windows mingw-gcc compiler.

---Original---
From: ***@***.***&gt;
Date: Sun, Jan 30, 2022 22:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [krystiankaluzny/Tanks] No Sound/Audio (Issue #7)




 
Ok thank you!
 I indeed looked for and didn't find, just wanted to be sure it's not hidden in this SDL stuff...
